1. Create a 1D array of numbers from 0 to 9.


In [1]:
import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
a
b=np.arange(1,10)
b
print(a)
print(b)
print(a.dtype)
print(b.dtype)

[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
int64
int64


2. Create a 3×3 numpy array of all True’s

In [2]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

3. Given an array as input, print only odd numbers as output

In [3]:
a=np.arange(1,20)
a
a[a%2==1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

4. Replace all odd numbers in arr with -2

In [4]:
a=np.arange(1,20)
a
a[a%2==1]=-2
a

array([-2,  2, -2,  4, -2,  6, -2,  8, -2, 10, -2, 12, -2, 14, -2, 16, -2,
       18, -2])

5. How to reshape an array?

In [5]:
# by using reshape method for example
c=np.arange(1,10)
print('before reshaping the method',c)
c=np.reshape(c,(3,3))
print('\nafter using reshape method\n',c)

before reshaping the method [1 2 3 4 5 6 7 8 9]

after using reshape method
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


6. Convert a 1D array to a 2D array with 2 rows

In [6]:
abc1=np.arange(4) #1D array
print(abc1)

abc2=np.resize(abc1,4).reshape(2,2) #2D array
print(abc2)

#Anther way to do 
np.reshape(abc1,(-1,2))

[0 1 2 3]
[[0 1]
 [2 3]]


array([[0, 1],
       [2, 3]])

7. Given an array a = [1,2,3,4,5,6,7,8,9] , create new array b from a such that b includes all odd numbers and 4 multiples.

In [7]:
b=a[(a%2==1) & (a%4==0)] 
b

array([], dtype=int64)

8. Given array, check if there are any null values and print them out.

In [8]:
nullvaluecheck=np.arange(10)
nullvaluescheck=np.append(nullvaluecheck,np.nan)
print(nullvaluescheck)
np.isnan(nullvaluescheck)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. nan]


array([False, False, False, False, False, False, False, False, False,
       False,  True])

9. How to replace all missing values with 0 in a numpy array?

In [9]:
np.nan_to_num(nullvaluescheck)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9., 0.])

10. How to find the count of each unique number in a NumPy array?

In [10]:
arrays_of_something=[1,2,3,4,4,4,3,2,1,4,5,7,8,9,9,9,19,0]
unique, counts = np.unique(arrays_of_something, return_counts=True)
print('Frequency of numbers')
print(np.asarray((unique,counts)).T)

Frequency of numbers
[[ 0  1]
 [ 1  2]
 [ 2  2]
 [ 3  2]
 [ 4  4]
 [ 5  1]
 [ 7  1]
 [ 8  1]
 [ 9  3]
 [19  1]]


11. How to convert a numeric to a categorical (text) array?


In [11]:
c=np.array(['1','2','3','4','5','6'],dtype=str)
print('before converting the array',c)
c=np.asfarray(c,int)
type(c)
print('After converting the array',c)

before converting the array ['1' '2' '3' '4' '5' '6']
After converting the array [1. 2. 3. 4. 5. 6.]


12. Write a program to print all numbers between 99 and 299 which are either divisible by 5 or 7. Exclude the elements which are divisible by both.

In [12]:
a=np.arange(99,299)
np.array(a)
b=a[(a%5==0)|(a%7==0)]
#print('printing numbers which are divisible by 5 or 7',b)
c=a[(a%5==0)&(a%7==0)]


13. Write a program to reverse an array and print (Don’t use inbuilt reverse functions)

In [13]:
def rev(l):
    r = []
    for i in l:
        r.insert(0, i)
    return r
a=[1,2,3,4]
rev(a)

[4, 3, 2, 1]